######### é”šç‚¹ start #######
# ç­–ç•¥ç»„ç›¸å…³
pr: &pr {type: select, proxies: [ğŸš€èŠ‚ç‚¹é€‰æ‹©, â«è‡ªåŠ¨é€‰æ‹©, ğŸ‡­ğŸ‡°é¦™æ¸¯, ğŸ‡­ğŸ‡°é¦™æ¸¯è‡ªåŠ¨é€‰æ‹©, ğŸ§‹å°æ¹¾, ğŸ§‹å°æ¹¾è‡ªåŠ¨é€‰æ‹©, ğŸ‡¯ğŸ‡µæ—¥æœ¬, ğŸ‡¯ğŸ‡µæ—¥æœ¬è‡ªåŠ¨é€‰æ‹©, ğŸ‡¸ğŸ‡¬æ–°åŠ å¡, ğŸ‡¸ğŸ‡¬æ–°åŠ å¡è‡ªåŠ¨é€‰æ‹©, ğŸ‡ºğŸ‡²ç¾å›½, ğŸ‡ºğŸ‡²ç¾å›½è‡ªåŠ¨é€‰æ‹©, â›³å…¨éƒ¨èŠ‚ç‚¹, ç›´è¿]}
#è¿™é‡Œæ˜¯è®¢é˜…æ›´æ–°å’Œå»¶è¿Ÿæµ‹è¯•ç›¸å…³çš„
p: &p {type: http, interval: 3600, health-check: {enable: true, url: "https://www.gstatic.com/generate_204", interval: 300}}
######### é”šç‚¹ end #######

# url é‡Œå¡«å†™è‡ªå·±çš„è®¢é˜…,åç§°ä¸èƒ½é‡å¤
proxy-providers:
  multisubs:
    <<: *p
    url: "https://ssb.chinnsenn.com/download/collection/allsubscriptions"
ipv6: true
allow-lan: true
mixed-port: 7890
external-controller: 127.0.0.1:9090
external-ui: ui
external-ui-url: "https://github.com/chinnsenn/metacubexd/archive/gh-pages.zip"

profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
  default-nameserver:
    - 223.5.5.5
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query


proxy-groups:
- {name: ğŸš€èŠ‚ç‚¹é€‰æ‹©, type: select, proxies: [â«è‡ªåŠ¨é€‰æ‹©, ç›´è¿, ğŸ‡­ğŸ‡°é¦™æ¸¯, ğŸ‡­ğŸ‡°é¦™æ¸¯è‡ªåŠ¨é€‰æ‹©, ğŸ§‹å°æ¹¾, ğŸ§‹å°æ¹¾è‡ªåŠ¨é€‰æ‹©, ğŸ‡¯ğŸ‡µæ—¥æœ¬, ğŸ‡¯ğŸ‡µæ—¥æœ¬è‡ªåŠ¨é€‰æ‹©, ğŸ‡¸ğŸ‡¬æ–°åŠ å¡, ğŸ‡¸ğŸ‡¬æ–°åŠ å¡è‡ªåŠ¨é€‰æ‹©, ğŸ‡ºğŸ‡²ç¾å›½, ğŸ‡ºğŸ‡²ç¾å›½è‡ªåŠ¨é€‰æ‹©, â›³å…¨éƒ¨èŠ‚ç‚¹], icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/Proxy.png"}
- {name: Google, <<: *pr, icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/Google_Search.png"}
- {name: Apple, <<: *pr, icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/Apple.png"}
- {name: Telegram, <<: *pr, icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/Telegram.png"}
- {name: OpenAI, <<: *pr, icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/ChatGPT.png"}
- {name: Anthropic, <<: *pr, icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/Anthropic.png"}
- {name: Twitter, <<: *pr, icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/Twitter.png"}
- {name: Wallet, <<: *pr, icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/Wallet.jpg"}
- {name: GitHub, <<: *pr, icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/GitHub.png"}
- {name: ehentai, <<: *pr, icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/Panda.png"}
- {name: å“”å“©å“”å“©, <<: *pr, icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/bilibili.png"}
- {name: å“”å“©ä¸œå—äºš, <<: *pr, icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/bilibili.png"}
- {name: å·´å“ˆå§†ç‰¹, <<: *pr, icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/Bahamut.png"}
- {name: YouTube, <<: *pr, icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/YouTube.png"}
- {name: Netflix, <<: *pr, icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/Netflix.png"}
- {name: Spotify, <<: *pr, icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/Spotify.png"}
- {name: DisneyPlus, <<: *pr, icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/Disney+.png"}
- {name: Tiktok, <<: *pr, icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/TikTok.png"}
- {name: DeepL, <<: *pr, icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/DeepL.jpg"}
- {name: Binance, <<: *pr, icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/Binance.jpg"}
- {name: Nintendo, <<: *pr, icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/Nintendo.png"}
- {name: Epic_Games, <<: *pr, icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/Epic_Games.png"}
- {name: PlayStation, <<: *pr, icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/PlayStation.png"}
- {name: Steamå›½é™…æœ, <<: *pr, icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/Steam.png"}
- {name: Steamå¤§é™†æœ, <<: *pr, icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/Steam.png"}
- {name: å›½å†…, type: select, proxies: [ç›´è¿, ğŸš€èŠ‚ç‚¹é€‰æ‹©, ğŸ‡­ğŸ‡°é¦™æ¸¯, ğŸ‡­ğŸ‡°é¦™æ¸¯è‡ªåŠ¨é€‰æ‹©, ğŸ§‹å°æ¹¾, ğŸ§‹å°æ¹¾è‡ªåŠ¨é€‰æ‹©, ğŸ‡¯ğŸ‡µæ—¥æœ¬, ğŸ‡¯ğŸ‡µæ—¥æœ¬è‡ªåŠ¨é€‰æ‹©, ğŸ‡¸ğŸ‡¬æ–°åŠ å¡, ğŸ‡¸ğŸ‡¬æ–°åŠ å¡è‡ªåŠ¨é€‰æ‹©, ğŸ‡ºğŸ‡²ç¾å›½, ğŸ‡ºğŸ‡²ç¾å›½è‡ªåŠ¨é€‰æ‹©, â›³å…¨éƒ¨èŠ‚ç‚¹, â«è‡ªåŠ¨é€‰æ‹©], icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/China_Map.png"}
- {name: å…¶ä»–, type: select, proxies: [ç›´è¿, ğŸš€èŠ‚ç‚¹é€‰æ‹©, ğŸ‡­ğŸ‡°é¦™æ¸¯, ğŸ‡­ğŸ‡°é¦™æ¸¯è‡ªåŠ¨é€‰æ‹©, ğŸ§‹å°æ¹¾, ğŸ§‹å°æ¹¾è‡ªåŠ¨é€‰æ‹©, ğŸ‡¯ğŸ‡µæ—¥æœ¬, ğŸ‡¯ğŸ‡µæ—¥æœ¬è‡ªåŠ¨é€‰æ‹©, ğŸ‡¸ğŸ‡¬æ–°åŠ å¡, ğŸ‡¸ğŸ‡¬æ–°åŠ å¡è‡ªåŠ¨é€‰æ‹©, ğŸ‡ºğŸ‡²ç¾å›½, ğŸ‡ºğŸ‡²ç¾å›½è‡ªåŠ¨é€‰æ‹©, â›³å…¨éƒ¨èŠ‚ç‚¹, â«è‡ªåŠ¨é€‰æ‹©], icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/Final.png"}
  #åˆ†éš”,ä¸‹é¢æ˜¯åœ°åŒºåˆ†ç»„
  
- {name: ğŸ‡­ğŸ‡°é¦™æ¸¯, type: select, include-all: true, filter: "(?i)æ¸¯|hk|hongkong|hong kong", icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/HK.png"}
- {name: ğŸ§‹å°æ¹¾, type: select, include-all: true, filter: "(?i)å°|tw|taiwan", icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/TW.png"}
- {name: ğŸ‡¯ğŸ‡µæ—¥æœ¬, type: select, include-all: true, filter: "(?i)æ—¥|jp|japan", icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/JP.png"}
- {name: ğŸ‡ºğŸ‡²ç¾å›½, type: select, include-all: true, filter: "(?i)ç¾|us|unitedstates|united states", icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/US.png"}
- {name: ğŸ‡¸ğŸ‡¬æ–°åŠ å¡, type: select, include-all: true, filter: "(?i)(æ–°|sg|singapore)", icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/SG.png"}
- {name: ğŸ‡°ğŸ‡·éŸ©å›½, type: select, include-all: true, filter: "(?i)kr|korea|kor|é¦–å°”|éŸ©|éŸ“", icon: "https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/KR.png"}
- {name: ğŸ‡¬ğŸ‡§è‹±å›½, type: select, include-all: true, filter: "(?i)uk|è‹±|ä¼¦æ•¦", icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/UK.png"}
- {name: ğŸ‡©ğŸ‡ªå¾·å›½, type: select, include-all: true, filter: "(?i)de|å¾·", icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/DE.png"}
- {name: ğŸ‡¨ğŸ‡¦åŠ æ‹¿å¤§, type: select, include-all: true, filter: "(?i)ca|canada|åŠ æ‹¿å¤§|æ«", icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/CA.png"}
- {name: ğŸ‡§ğŸ‡·å·´è¥¿, type: select, include-all: true, filter: "(?i)ba|å·´è¥¿", icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/BR.png"}
- {name: ğŸ‡®ğŸ‡³å°åº¦, type: select, include-all: true, filter: "(?i)in|å°åº¦", icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/IN.png"}
- {name: ğŸ‡³ğŸ‡±è·å…°, type: select, include-all: true, filter: "(?i)nl|è·å…°"}
- {name: ğŸ‡®ğŸ‡¹æ„å¤§åˆ©, type: select, include-all: true, filter: "(?i)it|æ„å¤§åˆ©|æ„"}
- {name: ğŸ‡¨ğŸ‡­ç‘å£«, type: select, include-all: true, filter: "(?i)ch|ç‘å£«"}
- {name: ğŸ‡«ğŸ‡·æ³•å›½, type: select, include-all: true, filter: "(?i)fr|æ³•|å·´é»", icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/FR.png"}
- {name: ğŸ‡¸ğŸ‡¦æ²™ç‰¹é˜¿æ‹‰ä¼¯, type: select, include-all: true, filter: "(?i)æ²™|æ²™ç‰¹|é˜¿æ‹‰ä¼¯"}
- {name: ğŸ‡®ğŸ‡±ä»¥è‰²åˆ—, type: select, include-all: true, filter: "(?i)il|ä»¥è‰²åˆ—"}
- {name: ğŸ‡¦ğŸ‡ªè¿ªæ‹œ, type: select, include-all: true, filter: "(?i)uae|è¿ªæ‹œ|æœæ‹œ|dubayy"}
- {name: ğŸ‡²ğŸ‡½å¢¨è¥¿å“¥, type: select, include-all: true, filter: "(?i)å¢¨è¥¿å“¥|mexico|mÃ©xico|mexican"}
- {name: ğŸ‡¨ğŸ‡±æ™ºåˆ©, type: select, include-all: true, filter: "(?i)æ™ºåˆ©|chile|cl"}
- {name: ğŸ‡¦ğŸ‡·é˜¿æ ¹å»·, type: select, include-all: true, filter: "(?i)é˜¿æ ¹å»·|argentina|ar", icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/AR.png"}
- {name: ğŸ‡¿ğŸ‡¦å—é, type: select, include-all: true, filter: "(?i)å—é|zuid-afrika"}
- {name: ğŸ‡¸ğŸ‡ªç‘å…¸, type: select, include-all: true, filter: "(?i)ç‘å…¸|sweden|sverige"}
- {name: ğŸ‡¹ğŸ‡·åœŸè€³å…¶, type: select, include-all: true, filter: "(?i)tr|åœŸè€³å…¶|åœŸ", icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/TR.png"}
- {name: ğŸ‡¦ğŸ‡ºæ¾³å¤§åˆ©äºš, type: select, include-all: true, filter: "(?i)åœŸæ¾³|æ¾³å¤§åˆ©äºš|æ¾³|aus", icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/AU.png"}
- {name: ğŸ‡µğŸ‡­è²å¾‹å®¾, type: select, include-all: true, filter: "(?i)è²|ph", icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/PH.png"}
- {name: ğŸ‡¹ğŸ‡­æ³°å›½, type: select, include-all: true, filter: "(?i)æ³°|th", icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/TH.png"}
- {name: ğŸ‡µğŸ‡°å·´åŸºæ–¯å¦, type: select, include-all: true, filter: "(?i)å·´åŸºæ–¯å¦|pk"}
- {name: ğŸ‡·ğŸ‡ºä¿„ç½—æ–¯, type: select, include-all: true, filter: "(?i)ä¿„|ä¿„ç½—æ–¯|rus|rf", icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/RU.png"}
- {name: ğŸ‡³ğŸ‡¬å°¼æ—¥åˆ©äºš, type: select, include-all: true, filter: "(?i)å°¼æ—¥åˆ©äºš|ngr"}
- {name: â«è‡ªåŠ¨é€‰æ‹©, type: url-test, include-all: true, filter: "(?i)^(?!.*(?:ç›´è¿)).*", icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/Auto.png"}
- {name: â›³å…¨éƒ¨èŠ‚ç‚¹, type: select, include-all: true, icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/Global.png"}
- {name: ğŸ‡­ğŸ‡°é¦™æ¸¯è‡ªåŠ¨é€‰æ‹©,type: url-test, include-all: true, filter: "(?i)æ¸¯|hk|hongkong|hong kong", icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/HK.png"}
- {name: ğŸ§‹å°æ¹¾è‡ªåŠ¨é€‰æ‹©,type: url-test, include-all: true, filter: "(?i)å°|tw|taiwan", icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/TW.png"}
- {name: ğŸ‡¯ğŸ‡µæ—¥æœ¬è‡ªåŠ¨é€‰æ‹©,type: url-test, include-all: true, filter: "(?i)æ—¥|jp|japan", icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/JP.png"}
- {name: ğŸ‡ºğŸ‡²ç¾å›½è‡ªåŠ¨é€‰æ‹©,type: url-test, include-all: true, filter: "(?i)ç¾|us|unitedstates|united states", icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/US.png"}
- {name: ğŸ‡¸ğŸ‡¬æ–°åŠ å¡è‡ªåŠ¨é€‰æ‹©,type: url-test, include-all: true, filter: "(?i)(æ–°|sg|singapore)", icon: "https://raw.githubusercontent.com/chinnsenn/Qure/master/IconSet/Color/SG.png"}

proxies:
- name: "ç›´è¿"
  type: direct
  udp: true

rules:
- GEOIP,lan,ç›´è¿,no-resolve
- RULE-SET,biliintl_domain,å“”å“©ä¸œå—äºš
- RULE-SET,ehentai_domain,ehentai
- RULE-SET,github_domain,GitHub
- RULE-SET,gitlab_domain,GitHub
- RULE-SET,twitter_domain,Twitter
- RULE-SET,youtube_domain,YouTube
- RULE-SET,disneyplus_domain,DisneyPlus
- RULE-SET,google_domain,Google
- RULE-SET,telegram_domain,Telegram
- RULE-SET,stripe_domain,Wallet
- RULE-SET,wise_domain,Wallet
- RULE-SET,openai_domain,OpenAI
- RULE-SET,anthropic_domain,Anthropic
- RULE-SET,netflix_domain,Netflix
- RULE-SET,bilibili_domain,å“”å“©å“”å“©
- RULE-SET,bahamut_domain,å·´å“ˆå§†ç‰¹
- RULE-SET,spotify_domain,Spotify
- RULE-SET,pixiv_domain,å…¶ä»–
- RULE-SET,geolocation-!cn,å…¶ä»–
- RULE-SET,nintendo_domain,Nintendo
- RULE-SET,epic_domain,Epic_Games
- RULE-SET,playstation_domain,PlayStation
- RULE-SET,steamintl_domain,Steamå›½é™…æœ
- RULE-SET,steamcn_domain,Steamå¤§é™†æœ
- RULE-SET,tiktok_domain,Tiktok
- RULE-SET,binance_domain,Binance
- RULE-SET,deepl_domain,DeepL

- RULE-SET,google_ip,Google
- RULE-SET,netflix_ip,Netflix
- RULE-SET,telegram_ip,Telegram
- RULE-SET,twitter_ip,Twitter
- RULE-SET,cn_domain,å›½å†…
- RULE-SET,cn_ip,å›½å†…
- MATCH,å…¶ä»–

rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: text}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: text}
rule-providers:
  private:
    <<: *domain
    url: "https://raw.githubusercontent.com/chinnsenn/meta-rules-dat/meta/geo/geosite/private.list"
  cn_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/chinnsenn/meta-rules-dat/meta/geo/geosite/cn.list"
  biliintl_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/chinnsenn/meta-rules-dat/meta/geo/geosite/biliintl.list"
  ehentai_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/chinnsenn/meta-rules-dat/meta/geo/geosite/ehentai.list"
  github_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/chinnsenn/meta-rules-dat/meta/geo/geosite/github.list"
  gitlab_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/chinnsenn/meta-rules-dat/meta/geo/geosite/gitlab.list"
  twitter_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/chinnsenn/meta-rules-dat/meta/geo/geosite/twitter.list"
  youtube_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/chinnsenn/meta-rules-dat/meta/geo/geosite/youtube.list"
  google_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/chinnsenn/meta-rules-dat/meta/geo/geosite/google.list"
  telegram_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/chinnsenn/meta-rules-dat/meta/geo/geosite/telegram.list"
  netflix_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/chinnsenn/meta-rules-dat/meta/geo/geosite/netflix.list"
  bilibili_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/chinnsenn/meta-rules-dat/meta/geo/geosite/bilibili.list"
  bahamut_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/chinnsenn/meta-rules-dat/meta/geo/geosite/bahamut.list"
  spotify_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/chinnsenn/meta-rules-dat/meta/geo/geosite/spotify.list"
  pixiv_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/chinnsenn/meta-rules-dat/meta/geo/geosite/pixiv.list"
  geolocation-!cn:
    <<: *domain
    url: "https://raw.githubusercontent.com/chinnsenn/meta-rules-dat/meta/geo/geosite/geolocation-!cn.list"
  nintendo_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/chinnsenn/meta-rules-dat/meta/geo/geosite/nintendo.list"
  epic_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/chinnsenn/meta-rules-dat/meta/geo/geosite/epicgames.list"
  playstation_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/chinnsenn/meta-rules-dat/meta/geo/geosite/playstation.list"
  steamintl_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/chinnsenn/meta-rules-dat/meta/geo/geosite/steam.list"
  steamcn_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/chinnsenn/meta-rules-dat/meta/geo/geosite/steam%40cn.list"
  tiktok_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/chinnsenn/meta-rules-dat/meta/geo/geosite/tiktok.list"
  disneyplus_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/chinnsenn/meta-rules-dat/meta/geo/geosite/disney.list"
  openai_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/chinnsenn/meta-rules-dat/meta/geo/geosite/openai.list"
  anthropic_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/chinnsenn/meta-rules-dat/meta/geo/geosite/anthropic.list"
  stripe_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/chinnsenn/meta-rules-dat/meta/geo/geosite/stripe.list"
  wise_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/chinnsenn/meta-rules-dat/meta/geo/geosite/wise.list"
  binance_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/chinnsenn/meta-rules-dat/meta/geo/geosite/binance.list"
  deepl_domain:
    <<: *domain
    url: "https://raw.githubusercontent.com/chinnsenn/meta-rules-dat/meta/geo/geosite/deepl.list"

  cn_ip:
    <<: *ip
    url: "https://raw.githubusercontent.com/chinnsenn/meta-rules-dat/meta/geo/geoip/cn.list"
  google_ip:
    <<: *ip
    url: "https://raw.githubusercontent.com/chinnsenn/meta-rules-dat/meta/geo/geoip/google.list"
  netflix_ip:
    <<: *ip
    url: "https://raw.githubusercontent.com/chinnsenn/meta-rules-dat/meta/geo/geoip/netflix.list"
  twitter_ip:
    <<: *ip
    url: "https://raw.githubusercontent.com/chinnsenn/meta-rules-dat/meta/geo/geoip/twitter.list"
  telegram_ip:
    <<: *ip
    url: "https://raw.githubusercontent.com/chinnsenn/meta-rules-dat/meta/geo/geoip/telegram.list"